# Generated by Django 2.2.10 on 2020-02-20 00:57

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('loc_id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('paid', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('details', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('status', models.CharField(choices=[('0', 'New'), ('1', 'Active'), ('2', 'Banned')], default=0, max_length=1)),
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('pp_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='DiningHall',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.Location')),
                ('hall_id', models.AutoField(primary_key=True, serialize=False)),
                ('hours', djongo.models.fields.ListField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('picture', models.URLField()),
            ],
            bases=('api.location',),
        ),
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('swipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('0', 'Available'), ('1', 'Sold'), ('2', 'Finalized'), ('3', 'Refunded')], default=0, max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('visibility', djongo.models.fields.ListField()),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.User')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.DiningHall')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('bid_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Accepted'), ('2', 'Confirmed')], default=0, max_length=1)),
                ('bid_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.User')),
                ('swipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Swipe')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.User')),
                ('pw', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('home_loc', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Location')),
            ],
            bases=('api.user',),
        ),
    ]
