# Generated by Django 2.2.10 on 2020-02-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='visible_from',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='visible_to',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
    ]
