# Generated by Django 2.2.10 on 2020-02-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='desired_time',
            field=models.TimeField(null=True),
        ),
    ]
