# Generated by Django 2.2.10 on 2020-03-09 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200220_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='location',
            new_name='hall_id',
        ),
        migrations.RenameField(
            model_name='swipe',
            old_name='location',
            new_name='hall_id',
        ),
    ]
