# Generated by Django 2.2.10 on 2020-03-09 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200308_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='home_loc',
        ),
        migrations.RemoveField(
            model_name='account',
            name='pw',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pp_email',
        ),
        migrations.AddField(
            model_name='account',
            name='cur_loc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Location'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='First Last', max_length=255),
            preserve_default=False,
        ),
    ]
