# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwipeX' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwipeX
  pod 'GoogleSignIn', '~> 5.0.0'
  pod 'Alamofire', '~> 5.0'
  pod 'SwiftyJSON'
  pod 'PhoneNumberKit', '~> 3.1'  
  pod 'MarqueeLabel'
  pod 'Stripe'
  target 'SwipeXTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwipeXUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
